package fixxy.comparison

import fixxy.comparison.subinterface.HasFieldComparisonOrNullForTagNumber
import fixxy.comparison.subinterface.HasFieldComparisonOrThrowForTagNumber
import fixxy.comparison.subinterface.MightHaveFieldComparisons

interface MessagePartComparison :
  MightHaveFieldComparisons,
  HasFieldComparisonOrNullForTagNumber,
  HasFieldComparisonOrThrowForTagNumber