package fixxy.comparison.comparer

import fixxy.comparison.subinterface.HasComparisonResultAcceptability
import fixxy.comparison.subinterface.HasComparisonResultMessage

interface FieldComparerResult :
  HasComparisonResultAcceptability,
  HasComparisonResultMessage